### ISSUE TITLE
Include the zip code in the cari API response

### ISSUE THREAD

**Issue by bluemiv** [drosanda/address-id-api#12]
Hi, drosanda!
Thank you for creating the API.

Can I just make one suggestion?
I think it would be good if the search API response value included the zip code as well.

[Request]

```
GET https://alamat.thecloudalert.com/api/cari/index/?keyword=Bali
```

[Reseponse]

```
{
    "status": 200,
    "message": "Berhasil",
    "result": [
        {
            "negara": "Indonesia",
            "provinsi": "Bali",
            "kabkota": "Kabupaten Badung",
            "kecamatan": "Abiansemal",
            "desakel": "Abiansemal"
            "zipCode": "12345"  <----- include the zip code
        },
    ]
}
```

**Comment by drosanda** [comment]
hi @bluemiv thanks for the feedback.

I will add it soon.

**Comment by drosanda** [comment]
deployed, you can check on this

https://alamat.thecloudalert.com/api/cari/index/?keyword=Abiansemal

cc: @bluemiv

**Comment by bluemiv** [comment]
Wow! really fast. thank you!
